Clock:
    - src/SonsOfPHP/Component/Clock/*

EventSourcing:
    - src/SonsOfPHP/Component/EventSourcing/*

FeatureToggle:
    - src/SonsOfPHP/Component/FeatureToggle/*

Money:
    - src/SonsOfPHP/Component/Money/*
